### ISSUE TITLE
import errors?

### ISSUE THREAD

**Issue by zachNA2** [HazyResearch/manifest#58]
## Description of the bug
Whenever I run the app and navigate to the url line 262 in manifest/manifest/api/app.py calls a metaseq resource. This isn't installed during setup.py which forces you to install metaseq from pypi which is a python2 library for genetic modeling. 

## To Reproduce
Build the manifest and run a module then go to the website at /

## Expected behavior
App actually loads?

## Error Logs/Screenshots
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 349, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'metaseq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "//manifest/manifest/api/app.py", line 262, in index
    fn = pkg_resources.resource_filename("metaseq", "service/index.html")
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1135, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 351, in get_provider
    __import__(moduleOrReq)
ModuleNotFoundError: No module named 'metaseq'

## Environment (please complete the following information)
 - WSL2 on FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04 image (docker)

**Comment by lorr1** [comment]
Is this still an issue?
